import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { getCached, getSyncQueue, setCached, withTimeout } from '../../data/local-first';
import { client } from '../../main';
import { headersWithAuth } from '../../utils/auth';
import { addDays, CLOUD_REFRESH_EVENT, isoDay, monthNow, READ_TIMEOUT, type CalendarData, type DailyBasic, type DailyNote, type Habit, type Log, type PomodoroSession, type RssActivity } from './model';
import { mergePendingBasics, mergePendingHabitData, normalizeBasics } from './sync';
import { LifeLayout } from './layout';

export function CalendarView({ year }: { year: boolean }) {
  const [month, setMonth] = useState(() => new URLSearchParams(window.location.search).get('month') || monthNow()); const [habits, setHabits] = useState<Habit[]>([]); const [logs, setLogs] = useState<Log[]>([]); const [sessions, setSessions] = useState<PomodoroSession[]>([]); const [notes, setNotes] = useState<DailyNote[]>([]); const [basics, setBasics] = useState<DailyBasic[]>([]); const [focused, setFocused] = useState<number | null>(null); const [selected, setSelected] = useState(() => { const requested = new URLSearchParams(window.location.search).get('month') || monthNow(); return requested === monthNow() ? isoDay() : `${requested}-01`; });
  useEffect(() => { const key = `life:calendar:${month}`; const apply = (value: CalendarData) => { setHabits(value.habits); setLogs(value.logs); setSessions(value.sessions); setNotes(value.notes || []); setBasics(value.basics || []); }; const load = async () => { const cached = await getCached<CalendarData>(key); if (cached) apply(cached.value); const [yearNumber, monthNumber] = month.split('-').map(Number); const start = new Date(yearNumber, monthNumber - 1, 1); const end = new Date(yearNumber, monthNumber, 1); try { const { data } = await withTimeout<any>(client.life.calendar.get({ query: { month, start: start.toISOString(), end: end.toISOString() }, headers: headersWithAuth() }) as Promise<any>, READ_TIMEOUT); if (data && typeof data !== 'string') { const merged = await mergePendingHabitData({ habits: data.habits as Habit[], logs: data.logs as Log[], notes: (data.notes || []) as DailyNote[] }, cached ? { habits: cached.value.habits, logs: cached.value.logs, notes: cached.value.notes || [] } : null); const basics: DailyBasic[] = []; for (const day of Array.from({ length: new Date(yearNumber, monthNumber, 0).getDate() }, (_, index) => `${month}-${String(index + 1).padStart(2, '0')}`)) basics.push(...await mergePendingBasics(day, (data.basics || []) as DailyBasic[], cached?.value.basics || [])); const sessions = [...data.sessions as PomodoroSession[]]; for (const queued of (await getSyncQueue()).filter(item => item.entity === 'pomodoro' && item.action === 'create')) { const payload = queued.payload as { startedAt: string; endedAt: string; focusMinutes: number; roundIndex: number; completed: boolean; taskName?: string; completedEarly?: boolean }; if (payload.startedAt.startsWith(month) && !sessions.some(value => new Date(value.startedAt).toISOString() === new Date(payload.startedAt).toISOString())) sessions.push({ ...payload, id: -(queued.id || Date.now()), startedAt: new Date(payload.startedAt), endedAt: new Date(payload.endedAt), completed: payload.completed ? 1 : 0, completedEarly: payload.completedEarly ? 1 : 0 }); } const next = { habits: merged.habits, logs: merged.logs, sessions, notes: merged.notes, basics }; apply(next); await setCached(key, next); } } catch {} }; void load(); const handler = () => { void load(); }; window.addEventListener(CLOUD_REFRESH_EVENT, handler); return () => window.removeEventListener(CLOUD_REFRESH_EVENT, handler); }, [month]);
  if (year) return <YearView />;
  const activeHabits = habits.filter(habit => habit.active);
  const activeHabitIds = new Set(activeHabits.map(habit => habit.id));
  const first = new Date(`${month}-01T00:00:00`); const dayCount = new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate(); const blanks = (first.getDay() + 6) % 7; const days = Array.from({ length: dayCount }, (_, i) => `${month}-${String(i + 1).padStart(2, '0')}`); const done = (date: string) => logs.filter(log => log.date === date && log.completed && activeHabitIds.has(log.habitId) && (!focused || log.habitId === focused)).length; const focusFor = (date: string) => sessions.filter(session => isoDay(new Date(session.startedAt)) === date && session.completed); const chosenSessions = focusFor(selected); const chosenLogs = logs.filter(log => log.date === selected && log.completed && activeHabitIds.has(log.habitId));
  const chosenNote = notes.find(note => note.date === selected); const chosenBasics = normalizeBasics(basics.filter(item => item.date === selected));
  return <LifeLayout section="calendar" title="日历" intro="当天的基础事项、便签、习惯和专注在同一条时间线上汇合。"><div className="calendar-tools"><input type="month" value={month} onChange={e => { setMonth(e.target.value); setSelected(`${e.target.value}-01`); }} /><select value={focused || ''} onChange={e => setFocused(e.target.value ? Number(e.target.value) : null)}><option value="">全部习惯</option>{activeHabits.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select><Link href="/life/year">全年视图</Link></div><div className="calendar-weekdays">{['一','二','三','四','五','六','日'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: blanks }, (_, i) => <span key={`blank-${i}`} />)}{days.map(date => <button key={date} onClick={() => setSelected(date)} className={`calendar-day ${done(date) ? 'done' : focused && date <= isoDay() ? 'missed' : ''} ${selected === date ? 'selected' : ''}`}><b>{Number(date.slice(-2))}</b><span>{done(date) ? `${done(date)} 项习惯` : ''}{notes.some(note => note.date === date && note.content) ? ' · 便签' : ''}{basics.some(item => item.date === date) ? ' · Today' : ''}</span><em>{focusFor(date).length ? `${focusFor(date).length} 🍅` : ''}</em></button>)}</div><section className="calendar-detail"><h2>{new Date(`${selected}T00:00:00`).toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' })}</h2>{chosenNote?.content && <p className="calendar-note">{chosenNote.content}</p>}<div><article><strong>Today</strong>{chosenBasics.length ? chosenBasics.map(item => <p key={item.id}>{item.completed ? '✓' : '○'} {item.content}</p>) : <p>没有基础事项</p>}</article><article><strong>习惯</strong>{chosenLogs.length ? chosenLogs.map(log => <p key={log.habitId}>✓ {activeHabits.find(h => h.id === log.habitId)?.name}</p>) : <p>没有完成记录</p>}</article><article><strong>专注</strong><p>{chosenSessions.length} 轮 · {chosenSessions.reduce((sum, item) => sum + item.focusMinutes, 0)} 分钟</p>{chosenSessions.map(item => <p key={item.id}>{new Date(item.startedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })} — {new Date(item.endedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</p>)}</article></div></section></LifeLayout>;
}

type YearSnapshot = { activity: Record<string, number>; habits: Array<{ id: number; name: string }>; logs: Log[]; sessions: PomodoroSession[]; rss: RssActivity[]; basics: DailyBasic[] };
function YearView() {
  const [year, setYear] = useState(new Date().getFullYear()); const [snapshot, setSnapshot] = useState<YearSnapshot>({ activity: {}, habits: [], logs: [], sessions: [], rss: [], basics: [] });
  useEffect(() => {
    const key = `life:year:v2:${year}`;
    const load = () => {
      void getCached<YearSnapshot>(key).then(cached => cached && setSnapshot(cached.value));
      const start = new Date(year, 0, 1); const end = new Date(year + 1, 0, 1);
      void withTimeout<any>(client.life.year.get({ query: { year: String(year), start: start.toISOString(), end: end.toISOString() }, headers: headersWithAuth() }) as Promise<any>, READ_TIMEOUT).then(({ data }) => {
        if (!data || typeof data === 'string') return;
        const activity: Record<string, number> = {}; const logs = data.logs as Log[]; const sessions = data.sessions as PomodoroSession[]; const rss = data.rss as RssActivity[]; const basics = (data.basics || []) as DailyBasic[];
        logs.forEach(log => { if (log.completed) activity[log.date] = (activity[log.date] || 0) + 1; });
        sessions.forEach(session => { if (session.completed) { const date = isoDay(new Date(session.startedAt)); activity[date] = (activity[date] || 0) + 1; } });
        rss.forEach(item => { [item.readAt, item.starredAt].forEach(value => { if (value) { const date = isoDay(new Date(value)); activity[date] = (activity[date] || 0) + 1; } }); });
        basics.forEach(item => { if (item.completed) activity[item.date] = (activity[item.date] || 0) + 1; });
        const next = { activity, habits: data.habits || [], logs, sessions, rss, basics }; setSnapshot(next); void setCached(key, next);
      }).catch(() => undefined);
    };
    load(); const handler = () => load(); window.addEventListener(CLOUD_REFRESH_EVENT, handler); return () => window.removeEventListener(CLOUD_REFRESH_EVENT, handler);
  }, [year]);
  const start = new Date(year, 0, 1); const cells = Array.from({ length: 371 }, (_, index) => { const date = addDays(start, index - ((start.getDay() + 6) % 7)); return date.getFullYear() === year ? isoDay(date) : ''; });
  const completedLogs = snapshot.logs.filter(log => log.completed); const completedSessions = snapshot.sessions.filter(session => session.completed); const completedBasics = snapshot.basics.filter(item => item.completed);
  const habitCounts = new Map<number, number>(); completedLogs.forEach(log => habitCounts.set(log.habitId, (habitCounts.get(log.habitId) || 0) + 1)); const stable = [...habitCounts.entries()].sort((a, b) => b[1] - a[1])[0];
  const monthly = Array.from({ length: 12 }, (_, month) => { const prefix = `${year}-${String(month + 1).padStart(2, '0')}`; return Object.entries(snapshot.activity).filter(([date]) => date.startsWith(prefix)).reduce((sum, [, count]) => sum + count, 0); }); const maxMonth = Math.max(1, ...monthly);
  return <LifeLayout section="calendar" title="年度回顾" intro="Calendar 看见这个月，Year 留下这一整年的生活痕迹。"><div className="year-tools"><button onClick={() => setYear(year - 1)}>← {year - 1}</button><strong>{year}</strong><button onClick={() => setYear(year + 1)}>{year + 1} →</button></div><section className="year-overview"><article><small>HABIT</small><strong>{completedLogs.length}</strong><span>{stable ? `最稳定：${snapshot.habits.find(item => item.id === stable[0])?.name || '习惯'} · ${stable[1]} 次` : '尚无完成记录'}</span></article><article><small>FOCUS</small><strong>{completedSessions.reduce((sum, item) => sum + item.focusMinutes, 0)} min</strong><span>{completedSessions.length} 轮专注</span></article><article><small>RSS</small><strong>{snapshot.rss.filter(item => item.readAt).length}</strong><span>{snapshot.rss.filter(item => item.starredAt).length} 次收藏</span></article><article><small>TODAY</small><strong>{new Set(completedBasics.map(item => item.date)).size}</strong><span>{completedBasics.length} 件基础事项</span></article></section><section className="year-heatmap"><header><strong>Life Heatmap</strong><span>{Object.keys(snapshot.activity).length} 个有记录的日子</span></header><div className="life-year-grid">{cells.map((date, index) => <span key={`${date}-${index}`} className={!date ? 'empty' : `level-${Math.min(4, snapshot.activity[date] || 0)}`} title={date ? `${date} · ${snapshot.activity[date] || 0} 条记录` : ''} />)}</div></section><section className="monthly-strip"><header><strong>月份</strong><span>点击进入当月日历</span></header>{monthly.map((value, index) => <Link key={index} href={`/life/calendar?month=${year}-${String(index + 1).padStart(2, '0')}`}><b>{String(index + 1).padStart(2, '0')}</b><i><span style={{ width: `${Math.max(4, value / maxMonth * 100)}%` }} /></i><em>{value}</em></Link>)}</section></LifeLayout>;
}
